services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
    restart: always
    command: --path.rootfs=/host
