services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/vasuper/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
